version: '3'
services:
  api:
    build: .
    container_name: api
    ports:
      - "8000:8000"
    volumes:
      - .:/app

  rabbitmq:
    image: "rabbitmq:3-management"
    ports:
      - "5672:5672"
      - "15672:15672"
